// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Tranquil Heart",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Tranquil Heart",
            targets: ["AppModule"],
            bundleIdentifier: "cn.SylviaZhang.Tranquil-Heart",
            teamIdentifier: "GCZJR2LRV2",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .note),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .music
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
//            dependencies: [
//                .product(name: "AudioKit", package: "audiokit")
//            ],
            path: ".",
            resources: [
                .process("AudioFiles")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
